/**
 * Importa a Temporada 2022, de uma planilha Google Sheets (link passado
 * pelo Organizador -- ver ticket 28). Mesmo padrao dos imports anteriores
 * (tickets 24/27): Temporada ja encerrada, sem mexer na Temporada aberta.
 * Premiacao real era percentual do pote (50%/30%, mesma estrutura das
 * Temporadas 2024.2/2025.2 do ticket 27) -- cada `entradaNoCaixa` ja vem
 * pronta da planilha, validada contra a coluna "$" original.
 *
 * Duas Partidas tem `entradaNoCaixa` AJUSTADO pra baixo em relacao ao "$"
 * da planilha (que so aplica a formula 50%/30% do pote, sem excecao):
 * 2022-03-22 (16 -> 14) e 2022-11-08 (18 -> 10) -- a propria planilha tem
 * notas manuais explicando que nesses dois dias a mesa entregou menos
 * dinheiro que o normal ("Nino entregou somente R$14 da mesa, pois
 * pagaram premio para o terceiro colocado" / "Entregaram somente R$10").
 * Confirmado: com esse ajuste, o saldo final bate exatamente com o
 * "TOTAL EM CAIXA" que a propria planilha registrava (R$0) -- sem o
 * ajuste, ficava R$10 acima.
 *
 * Uso:
 *   DATABASE_URL="postgres://..." npx tsx scripts/import-temporada-2022.ts [--dry-run]
 */
import { importarTemporadaHistorica, type PartidaImportada } from "./lib/importar-temporada-historica";

const DRY_RUN = process.argv.includes("--dry-run");

const PARTIDAS: PartidaImportada[] = [
  { data: "2022-02-15", entradaNoCaixa: 14, participantes: [{ nome: "Mica", posicao: 4, almas: 1, pagamento: true }, { nome: "Felipe", posicao: 6, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 7, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 1, almas: 2, pagamento: true }, { nome: "Nino", posicao: 3, almas: 2, pagamento: true }, { nome: "Galego", posicao: 2, almas: 0, pagamento: true }, { nome: "Turati", posicao: 5, almas: 0, pagamento: true }] },
  { data: "2022-02-22", entradaNoCaixa: 16, participantes: [{ nome: "Mica", posicao: 2, almas: 2, pagamento: true }, { nome: "Felipe", posicao: 7, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 3, almas: 1, pagamento: true }, { nome: "Edinho", posicao: 8, almas: 0, pagamento: true }, { nome: "Nino", posicao: 1, almas: 3, pagamento: true }, { nome: "Galego", posicao: 4, almas: 0, pagamento: true }, { nome: "Turati", posicao: 5, almas: 0, pagamento: true }, { nome: "Enio", posicao: 6, almas: 0, pagamento: true }] },
  { data: "2022-03-01", entradaNoCaixa: 18, participantes: [{ nome: "Mica", posicao: 9, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 4, almas: 1, pagamento: true }, { nome: "Danilo", posicao: 8, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 3, almas: 1, pagamento: true }, { nome: "Nino", posicao: 1, almas: 1, pagamento: true }, { nome: "Galego", posicao: 6, almas: 0, pagamento: true }, { nome: "Enio", posicao: 7, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 5, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 2, almas: 4, pagamento: true }] },
  { data: "2022-03-08", entradaNoCaixa: 16, participantes: [{ nome: "Mica", posicao: 6, almas: 1, pagamento: true }, { nome: "Felipe", posicao: 1, almas: 1, pagamento: true }, { nome: "Danilo", posicao: 5, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 4, almas: 0, pagamento: true }, { nome: "Nino", posicao: 7, almas: 0, pagamento: true }, { nome: "Galego", posicao: 8, almas: 0, pagamento: true }, { nome: "Enio", posicao: 2, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 3, almas: 3, pagamento: true }] },
  { data: "2022-03-15", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 1, almas: 4, pagamento: true }, { nome: "Felipe", posicao: 10, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 5, almas: 1, pagamento: true }, { nome: "Edinho", posicao: 9, almas: 0, pagamento: true }, { nome: "Nino", posicao: 4, almas: 1, pagamento: true }, { nome: "Galego", posicao: 2, almas: 2, pagamento: true }, { nome: "Turati", posicao: 8, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 7, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 3, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 6, almas: 0, pagamento: true }] },
  { data: "2022-03-22", entradaNoCaixa: 14, participantes: [{ nome: "Mica", posicao: 8, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 1, almas: 1, pagamento: true }, { nome: "Edinho", posicao: 3, almas: 1, pagamento: true }, { nome: "Nino", posicao: 2, almas: 3, pagamento: true }, { nome: "Galego", posicao: 5, almas: 0, pagamento: true }, { nome: "Turati", posicao: 7, almas: 0, pagamento: true }, { nome: "Enio", posicao: 4, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 6, almas: 0, pagamento: true }] },
  { data: "2022-03-29", entradaNoCaixa: 18, participantes: [{ nome: "Mica", posicao: 4, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 1, almas: 2, pagamento: true }, { nome: "Danilo", posicao: 2, almas: 3, pagamento: true }, { nome: "Edinho", posicao: 5, almas: 1, pagamento: true }, { nome: "Nino", posicao: 8, almas: 0, pagamento: true }, { nome: "Turati", posicao: 9, almas: 0, pagamento: true }, { nome: "Enio", posicao: 3, almas: 1, pagamento: true }, { nome: "Sergio", posicao: 6, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 7, almas: 0, pagamento: true }] },
  { data: "2022-04-05", entradaNoCaixa: 18, participantes: [{ nome: "Mica", posicao: 3, almas: 2, pagamento: true }, { nome: "Felipe", posicao: 5, almas: 1, pagamento: true }, { nome: "Danilo", posicao: 7, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 2, almas: 2, pagamento: true }, { nome: "Nino", posicao: 6, almas: 0, pagamento: true }, { nome: "Galego", posicao: 1, almas: 1, pagamento: true }, { nome: "Turati", posicao: 8, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 4, almas: 1, pagamento: true }, { nome: "Ueda", posicao: 9, almas: 0, pagamento: true }] },
  { data: "2022-04-12", entradaNoCaixa: 18, participantes: [{ nome: "Mica", posicao: 3, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 4, almas: 1, pagamento: true }, { nome: "Danilo", posicao: 9, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 6, almas: 0, pagamento: true }, { nome: "Nino", posicao: 1, almas: 5, pagamento: true }, { nome: "Galego", posicao: 7, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 2, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 8, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 5, almas: 0, pagamento: true }] },
  { data: "2022-04-19", entradaNoCaixa: 18, participantes: [{ nome: "Mica", posicao: 5, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 9, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 6, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 7, almas: 0, pagamento: true }, { nome: "Nino", posicao: 1, almas: 4, pagamento: true }, { nome: "Galego", posicao: 3, almas: 1, pagamento: true }, { nome: "Turati", posicao: 2, almas: 2, pagamento: true }, { nome: "Carlos", posicao: 8, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 4, almas: 0, pagamento: true }] },
  { data: "2022-04-26", entradaNoCaixa: 16, participantes: [{ nome: "Mica", posicao: 8, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 4, almas: 1, pagamento: true }, { nome: "Danilo", posicao: 5, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 6, almas: 0, pagamento: true }, { nome: "Nino", posicao: 7, almas: 0, pagamento: true }, { nome: "Galego", posicao: 3, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 2, almas: 1, pagamento: true }, { nome: "Ueda", posicao: 1, almas: 4, pagamento: true }] },
  { data: "2022-05-03", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 8, almas: 1, pagamento: true }, { nome: "Felipe", posicao: 1, almas: 2, pagamento: true }, { nome: "Danilo", posicao: 6, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 5, almas: 1, pagamento: true }, { nome: "Nino", posicao: 9, almas: 0, pagamento: true }, { nome: "Galego", posicao: 3, almas: 0, pagamento: true }, { nome: "Turati", posicao: 4, almas: 1, pagamento: true }, { nome: "Enio", posicao: 2, almas: 3, pagamento: true }, { nome: "Carlos", posicao: 10, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 7, almas: 0, pagamento: true }] },
  { data: "2022-05-10", entradaNoCaixa: 22, participantes: [{ nome: "Mica", posicao: 5, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 10, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 6, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 1, almas: 6, pagamento: true }, { nome: "Nino", posicao: 9, almas: 1, pagamento: true }, { nome: "Galego", posicao: 2, almas: 2, pagamento: true }, { nome: "Turati", posicao: 11, almas: 0, pagamento: true }, { nome: "Enio", posicao: 7, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 8, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 4, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 3, almas: 0, pagamento: true }] },
  { data: "2022-05-17", entradaNoCaixa: 22, participantes: [{ nome: "Mica", posicao: 5, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 8, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 9, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 7, almas: 0, pagamento: true }, { nome: "Nino", posicao: 3, almas: 0, pagamento: true }, { nome: "Galego", posicao: 11, almas: 0, pagamento: true }, { nome: "Turati", posicao: 10, almas: 0, pagamento: true }, { nome: "Enio", posicao: 2, almas: 2, pagamento: true }, { nome: "Sergio", posicao: 6, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 1, almas: 5, pagamento: true }, { nome: "Ueda", posicao: 4, almas: 1, pagamento: true }] },
  { data: "2022-05-24", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 3, almas: 4, pagamento: true }, { nome: "Felipe", posicao: 1, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 7, almas: 1, pagamento: true }, { nome: "Edinho", posicao: 8, almas: 0, pagamento: true }, { nome: "Nino", posicao: 5, almas: 0, pagamento: true }, { nome: "Galego", posicao: 10, almas: 0, pagamento: true }, { nome: "Enio", posicao: 4, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 2, almas: 3, pagamento: true }, { nome: "Carlos", posicao: 9, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 6, almas: 0, pagamento: true }] },
  { data: "2022-05-31", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 3, almas: 1, pagamento: true }, { nome: "Felipe", posicao: 1, almas: 2, pagamento: true }, { nome: "Danilo", posicao: 10, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 5, almas: 1, pagamento: true }, { nome: "Nino", posicao: 2, almas: 2, pagamento: true }, { nome: "Galego", posicao: 6, almas: 0, pagamento: true }, { nome: "Turati", posicao: 7, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 4, almas: 2, pagamento: true }, { nome: "Carlos", posicao: 9, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 8, almas: 0, pagamento: true }] },
  { data: "2022-06-07", entradaNoCaixa: 18, participantes: [{ nome: "Mica", posicao: 8, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 9, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 7, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 3, almas: 1, pagamento: true }, { nome: "Nino", posicao: 4, almas: 1, pagamento: true }, { nome: "Galego", posicao: 6, almas: 0, pagamento: true }, { nome: "Enio", posicao: 2, almas: 2, pagamento: true }, { nome: "Carlos", posicao: 1, almas: 2, pagamento: true }, { nome: "Ueda", posicao: 5, almas: 1, pagamento: true }] },
  { data: "2022-06-14", entradaNoCaixa: 18, participantes: [{ nome: "Mica", posicao: 9, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 8, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 6, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 3, almas: 2, pagamento: true }, { nome: "Nino", posicao: 2, almas: 2, pagamento: true }, { nome: "Galego", posicao: 5, almas: 0, pagamento: true }, { nome: "Turati", posicao: 1, almas: 3, pagamento: true }, { nome: "Sergio", posicao: 4, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 7, almas: 0, pagamento: true }] },
  { data: "2022-06-21", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 3, almas: 3, pagamento: true }, { nome: "Felipe", posicao: 6, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 9, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 4, almas: 0, pagamento: true }, { nome: "Nino", posicao: 10, almas: 0, pagamento: true }, { nome: "Galego", posicao: 7, almas: 0, pagamento: true }, { nome: "Turati", posicao: 5, almas: 0, pagamento: true }, { nome: "Enio", posicao: 2, almas: 2, pagamento: true }, { nome: "Carlos", posicao: 8, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 1, almas: 3, pagamento: true }] },
  { data: "2022-06-28", entradaNoCaixa: 16, participantes: [{ nome: "Mica", posicao: 6, almas: 1, pagamento: true }, { nome: "Danilo", posicao: 3, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 8, almas: 0, pagamento: true }, { nome: "Nino", posicao: 1, almas: 3, pagamento: true }, { nome: "Galego", posicao: 5, almas: 0, pagamento: true }, { nome: "Turati", posicao: 4, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 7, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 2, almas: 2, pagamento: true }] },
  { data: "2022-07-05", entradaNoCaixa: 22, participantes: [{ nome: "Mica", posicao: 4, almas: 2, pagamento: true }, { nome: "Felipe", posicao: 3, almas: 2, pagamento: true }, { nome: "Danilo", posicao: 5, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 6, almas: 0, pagamento: true }, { nome: "Nino", posicao: 2, almas: 4, pagamento: true }, { nome: "Galego", posicao: 10, almas: 0, pagamento: true }, { nome: "Turati", posicao: 8, almas: 0, pagamento: true }, { nome: "Enio", posicao: 7, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 1, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 11, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 9, almas: 0, pagamento: true }] },
  { data: "2022-07-12", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 5, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 9, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 7, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 2, almas: 2, pagamento: true }, { nome: "Nino", posicao: 3, almas: 0, pagamento: true }, { nome: "Galego", posicao: 1, almas: 4, pagamento: true }, { nome: "Turati", posicao: 10, almas: 0, pagamento: true }, { nome: "Enio", posicao: 6, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 4, almas: 1, pagamento: true }, { nome: "Ueda", posicao: 8, almas: 1, pagamento: true }] },
  { data: "2022-07-19", entradaNoCaixa: 22, participantes: [{ nome: "Mica", posicao: 4, almas: 1, pagamento: true }, { nome: "Felipe", posicao: 10, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 2, almas: 4, pagamento: true }, { nome: "Edinho", posicao: 7, almas: 0, pagamento: true }, { nome: "Nino", posicao: 5, almas: 0, pagamento: true }, { nome: "Galego", posicao: 6, almas: 0, pagamento: true }, { nome: "Turati", posicao: 11, almas: 0, pagamento: true }, { nome: "Enio", posicao: 8, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 3, almas: 2, pagamento: true }, { nome: "Carlos", posicao: 9, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 1, almas: 2, pagamento: true }] },
  { data: "2022-07-26", entradaNoCaixa: 16, participantes: [{ nome: "Mica", posicao: 8, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 6, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 2, almas: 2, pagamento: true }, { nome: "Nino", posicao: 1, almas: 2, pagamento: true }, { nome: "Galego", posicao: 7, almas: 0, pagamento: true }, { nome: "Turati", posicao: 5, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 4, almas: 1, pagamento: true }, { nome: "Ueda", posicao: 3, almas: 1, pagamento: true }] },
  { data: "2022-08-02", entradaNoCaixa: 22, participantes: [{ nome: "Mica", posicao: 10, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 9, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 7, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 4, almas: 0, pagamento: true }, { nome: "Nino", posicao: 1, almas: 4, pagamento: true }, { nome: "Galego", posicao: 8, almas: 0, pagamento: true }, { nome: "Turati", posicao: 3, almas: 2, pagamento: true }, { nome: "Enio", posicao: 5, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 2, almas: 2, pagamento: true }, { nome: "Carlos", posicao: 11, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 6, almas: 1, pagamento: true }] },
  { data: "2022-08-09", entradaNoCaixa: 18, participantes: [{ nome: "Felipe", posicao: 9, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 4, almas: 1, pagamento: true }, { nome: "Nino", posicao: 3, almas: 3, pagamento: true }, { nome: "Galego", posicao: 8, almas: 0, pagamento: true }, { nome: "Turati", posicao: 10, almas: 0, pagamento: true }, { nome: "Enio", posicao: 5, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 1, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 6, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 2, almas: 2, pagamento: true }] },
  { data: "2022-08-16", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 9, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 1, almas: 2, pagamento: true }, { nome: "Edinho", posicao: 10, almas: 0, pagamento: true }, { nome: "Nino", posicao: 5, almas: 3, pagamento: true }, { nome: "Galego", posicao: 8, almas: 0, pagamento: true }, { nome: "Turati", posicao: 4, almas: 0, pagamento: true }, { nome: "Enio", posicao: 3, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 7, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 6, almas: 1, pagamento: true }, { nome: "Ueda", posicao: 2, almas: 2, pagamento: true }] },
  { data: "2022-08-23", entradaNoCaixa: 22, participantes: [{ nome: "Mica", posicao: 1, almas: 2, pagamento: true }, { nome: "Felipe", posicao: 8, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 7, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 3, almas: 1, pagamento: true }, { nome: "Nino", posicao: 2, almas: 2, pagamento: true }, { nome: "Galego", posicao: 4, almas: 1, pagamento: true }, { nome: "Turati", posicao: 11, almas: 0, pagamento: true }, { nome: "Enio", posicao: 5, almas: 2, pagamento: true }, { nome: "Sergio", posicao: 6, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 9, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 10, almas: 0, pagamento: true }] },
  { data: "2022-08-30", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 3, almas: 1, pagamento: true }, { nome: "Felipe", posicao: 2, almas: 2, pagamento: true }, { nome: "Danilo", posicao: 8, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 1, almas: 1, pagamento: true }, { nome: "Nino", posicao: 7, almas: 0, pagamento: true }, { nome: "Galego", posicao: 5, almas: 1, pagamento: true }, { nome: "Turati", posicao: 6, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 9, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 4, almas: 3, pagamento: true }, { nome: "Ueda", posicao: 10, almas: 0, pagamento: true }] },
  { data: "2022-09-06", entradaNoCaixa: 10, participantes: [{ nome: "Felipe", posicao: 5, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 4, almas: 0, pagamento: true }, { nome: "Nino", posicao: 1, almas: 2, pagamento: true }, { nome: "Sergio", posicao: 2, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 3, almas: 1, pagamento: true }] },
  { data: "2022-09-13", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 3, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 5, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 5, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 5, almas: 0, pagamento: true }, { nome: "Nino", posicao: 2, almas: 0, pagamento: true }, { nome: "Turati", posicao: 5, almas: 0, pagamento: true }, { nome: "Enio", posicao: 5, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 5, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 1, almas: 5, pagamento: true }, { nome: "Ueda", posicao: 4, almas: 0, pagamento: true }] },
  { data: "2022-09-20", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 8, almas: 1, pagamento: true }, { nome: "Felipe", posicao: 4, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 9, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 7, almas: 0, pagamento: true }, { nome: "Nino", posicao: 3, almas: 0, pagamento: true }, { nome: "Turati", posicao: 5, almas: 0, pagamento: true }, { nome: "Enio", posicao: 2, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 6, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 10, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 1, almas: 7, pagamento: true }] },
  { data: "2022-09-27", entradaNoCaixa: 18, participantes: [{ nome: "Mica", posicao: 9, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 1, almas: 1, pagamento: true }, { nome: "Danilo", posicao: 5, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 8, almas: 0, pagamento: true }, { nome: "Nino", posicao: 6, almas: 0, pagamento: true }, { nome: "Turati", posicao: 3, almas: 1, pagamento: true }, { nome: "Enio", posicao: 2, almas: 2, pagamento: true }, { nome: "Carlos", posicao: 4, almas: 3, pagamento: true }, { nome: "Ueda", posicao: 7, almas: 0, pagamento: true }] },
  { data: "2022-10-04", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 8, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 1, almas: 2, pagamento: true }, { nome: "Danilo", posicao: 2, almas: 2, pagamento: true }, { nome: "Edinho", posicao: 7, almas: 0, pagamento: true }, { nome: "Nino", posicao: 9, almas: 0, pagamento: true }, { nome: "Turati", posicao: 3, almas: 2, pagamento: true }, { nome: "Enio", posicao: 6, almas: 1, pagamento: true }, { nome: "Sergio", posicao: 4, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 10, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 5, almas: 0, pagamento: true }] },
  { data: "2022-10-18", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 7, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 8, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 2, almas: 3, pagamento: true }, { nome: "Nino", posicao: 1, almas: 2, pagamento: true }, { nome: "Galego", posicao: 6, almas: 0, pagamento: true }, { nome: "Turati", posicao: 10, almas: 0, pagamento: true }, { nome: "Enio", posicao: 3, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 5, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 9, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 4, almas: 3, pagamento: true }] },
  { data: "2022-10-25", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 1, almas: 5, pagamento: true }, { nome: "Felipe", posicao: 6, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 4, almas: 1, pagamento: true }, { nome: "Edinho", posicao: 7, almas: 0, pagamento: true }, { nome: "Nino", posicao: 10, almas: 0, pagamento: true }, { nome: "Galego", posicao: 8, almas: 0, pagamento: true }, { nome: "Turati", posicao: 9, almas: 0, pagamento: true }, { nome: "Enio", posicao: 5, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 3, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 2, almas: 2, pagamento: true }] },
  { data: "2022-11-08", entradaNoCaixa: 10, participantes: [{ nome: "Mica", posicao: 6, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 9, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 1, almas: 4, pagamento: true }, { nome: "Nino", posicao: 8, almas: 0, pagamento: true }, { nome: "Galego", posicao: 7, almas: 0, pagamento: true }, { nome: "Turati", posicao: 4, almas: 0, pagamento: true }, { nome: "Enio", posicao: 5, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 3, almas: 1, pagamento: true }, { nome: "Ueda", posicao: 2, almas: 2, pagamento: true }] },
  { data: "2022-11-22", entradaNoCaixa: 20, participantes: [{ nome: "Mica", posicao: 10, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 9, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 5, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 7, almas: 0, pagamento: true }, { nome: "Nino", posicao: 2, almas: 1, pagamento: true }, { nome: "Galego", posicao: 1, almas: 4, pagamento: true }, { nome: "Enio", posicao: 6, almas: 1, pagamento: true }, { nome: "Sergio", posicao: 3, almas: 1, pagamento: true }, { nome: "Carlos", posicao: 8, almas: 1, pagamento: true }, { nome: "Ueda", posicao: 4, almas: 0, pagamento: true }] },
  { data: "2022-11-29", entradaNoCaixa: 22, participantes: [{ nome: "Mica", posicao: 11, almas: 0, pagamento: true }, { nome: "Felipe", posicao: 6, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 7, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 10, almas: 0, pagamento: true }, { nome: "Nino", posicao: 2, almas: 0, pagamento: true }, { nome: "Galego", posicao: 8, almas: 0, pagamento: true }, { nome: "Turati", posicao: 5, almas: 0, pagamento: true }, { nome: "Enio", posicao: 4, almas: 0, pagamento: true }, { nome: "Sergio", posicao: 1, almas: 6, pagamento: true }, { nome: "Carlos", posicao: 9, almas: 0, pagamento: true }, { nome: "Ueda", posicao: 3, almas: 3, pagamento: true }] },
  { data: "2022-12-06", entradaNoCaixa: 22, participantes: [{ nome: "Mica", posicao: 6, almas: 1, pagamento: true }, { nome: "Felipe", posicao: 9, almas: 0, pagamento: true }, { nome: "Danilo", posicao: 11, almas: 0, pagamento: true }, { nome: "Edinho", posicao: 8, almas: 0, pagamento: true }, { nome: "Nino", posicao: 2, almas: 2, pagamento: true }, { nome: "Galego", posicao: 1, almas: 2, pagamento: true }, { nome: "Turati", posicao: 4, almas: 1, pagamento: true }, { nome: "Enio", posicao: 5, almas: 2, pagamento: true }, { nome: "Sergio", posicao: 10, almas: 0, pagamento: true }, { nome: "Carlos", posicao: 7, almas: 1, pagamento: true }, { nome: "Ueda", posicao: 3, almas: 0, pagamento: true }] },
];

importarTemporadaHistorica({
  rotulo: "2022",
  partidas: PARTIDAS,
  parametros: {
    tabelaDePontos: [
      [1, 23], [2, 17], [3, 12], [4, 8], [5, 5], [6, 3], [7, 2],
      [8, 1], [9, 1], [10, 1], [11, 1], [12, 1],
    ],
    valorDaPartida: 10,
    multiplicadorPremiacaoPrimeiro: 0,
    multiplicadorPremiacaoSegundo: 0,
    estruturaDeBlinds: [],
    fichasIniciais: [],
  },
  saidasManuais: [
    { data: "2022-05-19", descricao: "Compra de novo baralho", valor: 40 },
    { data: "2022-12-13", descricao: "Premiacao de fim de temporada", valor: 435 },
    { data: "2022-12-13", descricao: "Pizza, cerveja e gelo (confraternizacao de fim de temporada)", valor: 271 }
  ],
  totaisEsperados: {
    Enio: { pontos: 253, almas: 20 },
    Nino: { pontos: 523, almas: 53 },
    Mica: { pontos: 283, almas: 33 },
    Felipe: { pontos: 282, almas: 18 },
    Turati: { pontos: 182, almas: 12 },
    Galego: { pontos: 265, almas: 18 },
    Sergio: { pontos: 295, almas: 25 },
    Carlos: { pontos: 208, almas: 30 },
    Ueda: { pontos: 351, almas: 38 },
    Danilo: { pontos: 238, almas: 17 },
    Edinho: { pontos: 326, almas: 31 }
  },
  dryRun: DRY_RUN,
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
